### ISSUE TITLE
Vim quine?

### ISSUE THREAD

**Issue by DialFrost** [MakeNowJust/quine#7]
I don't happen to see any vim quine here, maybe you can add it? Thanks! :3

**Comment by makenowjust** [comment]
It is easy because VimL has lambda syntax for version 8.
Quick example:

```viml
:echo{s->s..nr2char(34)..s..nr2char(34)..')'}(":echo{s->s..nr2char(34)..s..nr2char(34)..')'}(")
```

Also, we can write Quine by adroitness using registers. See https://codegolf.stackexchange.com/questions/69/golf-you-a-quine-for-great-good#answer-95910.

Since there is no VimL interpreter without launching the editor, this is not in the repository.

**Comment by makenowjust** [comment]
I answered. Close.
